# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Test App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CryptoSwift'
  pod 'SwiftyRSA'
  pod 'URLImage'

  # Pods for Test App

  target 'Test AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test AppUITests' do
    # Pods for testing
  end

end
